[package]
name = "installer"
version = "0.1.0"
description = "Instalador de Lumi y Lumi Indexer"
authors = ["Lumi"]
license = "AGPL-3.0-or-later"
repository = ""
edition = "2021"
rust-version = "1.77.2"

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.11.3", features = [] }
tauri-plugin-log = "2"
tauri-plugin-dialog = "2"
lumi-installer = { path = "../../crates/lumi-installer" }
lumi-proto = { path = "../../crates/lumi-proto" }
mslnk = "0.1.8"
winreg = "0.56.0"
windows-sys = { version = "0.61.2", features = ["Win32_UI_WindowsAndMessaging", "Win32_Foundation"] }
