[package]
name = "app"
version = "2.0.17"
description = "A Tauri App"
authors = ["you"]
license = "AGPL-3.0-or-later"
repository = ""
edition = "2021"
rust-version = "1.77.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.11.3", features = [] }
tauri-plugin-log = "2"
tauri-plugin-dialog = "2"
tauri-plugin-opener = "2"
tauri-plugin-autostart = "2"
lumi-proto = { path = "../../crates/lumi-proto" }
lumi-installer = { path = "../../crates/lumi-installer" }
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls-manual-roots", "rustls-tls-native-roots", "stream", "multipart"] }
rustls = "0.23"
tokio = { version = "1", features = ["full"] }
futures-util = "0.3"
http = "1"
base64 = "0.22"
